port: 8765
authentication: false
tokens:
  example-token: "remove me"
callbackUrl: "https://example.test/"
certificatePath: null
callbackEndpoints:
  server:
    online: "server/online"
  player:
    join: "player/join/{uuid}"
    leave: "player/leave/{uuid}"