port: 8765
authentication: false
tokens:
  example-token: "remove me"
httpEvents:
  secure: true
  domain: "example.test"
  port: 8000
  endpoints:
    server:
      online: "/server/online"
    player:
      online: "/player/join"
      offline: "/player/leave"